Sensedia/massadedados

F2_Consentimento/post-consents-201-1.json
Adicionando a variável brandID e ajustando as variáveis de datas.
=> Adicionando a variável brandID e ajustando as datas do consentimento.

F2_Dados Cadastrais/get-personal-identifications-200-1.json, F2_Dados Cadastrais/get-personal-identifications-200-10.json, F2_Dados Cadastrais/get-personal-identifications-200-11.json, F2_Dados Cadastrais/get-personal-identifications-200-12.json, F2_Dados Cadastrais/get-personal-identifications-200-2.json, F2_Dados Cadastrais/get-personal-identifications-200-3.json, F2_Dados Cadastrais/get-personal-identifications-200-4.json, F2_Dados Cadastrais/get-personal-identifications-200-5.json, F2_Dados Cadastrais/get-personal-identifications-200-6.json, F2_Dados Cadastrais/get-personal-identifications-200-7.json, F2_Dados Cadastrais/get-personal-identifications-200-8.json, F2_Dados Cadastrais/get-personal-identifications-200-9.json, F2_Dados Cadastrais/get-personal-qualifications-200-10.json, F2_Dados Cadastrais/get-personal-qualifications-200-11.json, F2_Dados Cadastrais/get-personal-qualifications-200-12.json, F2_Dados Cadastrais/get-personal-qualifications-200-2.json, F2_Dados Cadastrais/get-personal-qualifications-200-3.json, F2_Dados Cadastrais/get-personal-qualifications-200-4.json, F2_Dados Cadastrais/get-personal-qualifications-200-5.json, F2_Dados Cadastrais/get-personal-qualifications-200-6.json, F2_Dados Cadastrais/get-personal-qualifications-200-7.json, F2_Dados Cadastrais/get-personal-qualifications-200-8.json, F2_Dados Cadastrais/get-personal-qualifications-200-9.json
Subindo as massas de dados cadastrais dos endpoints de personal identifications e personal qualifications.
=> Dados cadastrais - Personal identifications e qualifications

F2_Dados Cadastrais/get-business-identifications-200-1.json, F2_Dados Cadastrais/get-personal-financial-relations-200-1.json, F2_Dados Cadastrais/get-personal-financial-relations-200-10.json, F2_Dados Cadastrais/get-personal-financial-relations-200-11.json, F2_Dados Cadastrais/get-personal-financial-relations-200-12.json, F2_Dados Cadastrais/get-personal-financial-relations-200-2.json, F2_Dados Cadastrais/get-personal-financial-relations-200-3.json, F2_Dados Cadastrais/get-personal-financial-relations-200-4.json, F2_Dados Cadastrais/get-personal-financial-relations-200-5.json, F2_Dados Cadastrais/get-personal-financial-relations-200-6.json, F2_Dados Cadastrais/get-personal-financial-relations-200-7.json, F2_Dados Cadastrais/get-personal-financial-relations-200-8.json, F2_Dados Cadastrais/get-personal-financial-relations-200-9.json
Adicionando as massas de personal-financial-relations e ajustando os dados da instituição bancária de business-identifications-200-1.json.
=> Dados cadastrais

F2_Consentimento/get-consents-{consentId}/get-consents-consentId-11.1.json, F2_Consentimento/post-consents/post-consents-11.1.json, F2_Dados Cadastrais/get-customers-personal-financial-relations-11.1.json, F2_Dados Cadastrais/get-customers-personal-identifications-11.1.json, F2_Dados Cadastrais/get-customers-personal-qualifications-11.1.json
Adicionando consentimentos de loans para Sarah.
=> Consentimentos de loans para Sarah

F2_Consentimento/post-consents/post-consents-1.1.json, F2_Consentimento/post-consents/post-consents-10.1.json, F2_Consentimento/post-consents/post-consents-10.2.json, F2_Consentimento/post-consents/post-consents-11.1.json, F2_Consentimento/post-consents/post-consents-12.1.json, F2_Consentimento/post-consents/post-consents-13.1.json, F2_Consentimento/post-consents/post-consents-14.1.json, F2_Consentimento/post-consents/post-consents-15.1.json, F2_Consentimento/post-consents/post-consents-16.1.json, F2_Consentimento/post-consents/post-consents-17.1.json, F2_Consentimento/post-consents/post-consents-18.1.json, F2_Consentimento/post-consents/post-consents-19.1.json, F2_Consentimento/post-consents/post-consents-19.2.json, F2_Consentimento/post-consents/post-consents-19.3.json, F2_Consentimento/post-consents/post-consents-2.1.json, F2_Consentimento/post-consents/post-consents-20.1.json, F2_Consentimento/post-consents/post-consents-21.1.json, F2_Consentimento/post-consents/post-consents-22.1.json, F2_Consentimento/post-consents/post-consents-23.1.json, F2_Consentimento/post-consents/post-consents-24.1.json, F2_Consentimento/post-consents/post-consents-25.1.json, F2_Consentimento/post-consents/post-consents-3.1.json, F2_Consentimento/post-consents/post-consents-4.1.json, F2_Consentimento/post-consents/post-consents-5.1.json, F2_Consentimento/post-consents/post-consents-6.1.json, F2_Consentimento/post-consents/post-consents-7.1.json, F2_Consentimento/post-consents/post-consents-8.1.json, F2_Consentimento/post-consents/post-consents-9.1.json
Conforme solicitado pelo cliente estes campos foram removidos. 
Permanece agora apenas o campo de expiration.
=> Consentimento - Remoção dos campos de transactionDateTime

F3_Pagamentos/Scenario-05/scenario-05.1-post-consents.json, F3_Pagamentos/Scenario-05/scenario-05.2-get-consents.json, F3_Pagamentos/Scenario-05/scenario-05.3-post-pix-payments.json, F3_Pagamentos/Scenario-05/scenario-05.4-get-pix-payments.json
Adicionando as massas do cenário 05 da API de pagamento.
=> Fase 3 - Cenário 05  da API de pagamentos

f3-pagamentos/README.md, f3-pagamentos/pagamentos.txt, f3-pagamentos/scenario-01/readme.md, f3-pagamentos/scenario-01/scenario-01.1-post-consents.json, f3-pagamentos/scenario-01/scenario-01.2-get-consents.json, f3-pagamentos/scenario-01/scenario-01.3-post-pix-payments.json, f3-pagamentos/scenario-01/scenario-01.4-get-pix-payments.json
=> cenario 1 - 1.0.1-rc1.1

f3-pagamentos/README.md, f3-pagamentos/scenario-03/readme.md, f3-pagamentos/scenario-03/scenario-03.1-post-consents.json, f3-pagamentos/scenario-03/scenario-03.2-get-consents.json, f3-pagamentos/scenario-03/scenario-03.3-post-pix-payments.json, f3-pagamentos/scenario-03/scenario-03.4-get-pix-payments.json
=> 1.0.1-rc1.1 DICT chave cpf

f3-pagamentos/README.md, f3-pagamentos/scenario-04/readme.md, f3-pagamentos/scenario-04/scenario-04.1-post-consents.json, f3-pagamentos/scenario-04/scenario-04.2-post-consents.json, f3-pagamentos/scenario-04/scenario-04.3-post-pix-payments.json, f3-pagamentos/scenario-04/scenario-04.4-get-pix-payments.json
1.0.1-rc1.1 DICT chave celular
=> 1.0.1-rc1.1 DICT chave celular

f3-pagamentos/README.md, f3-pagamentos/scenario-05/readme.md, f3-pagamentos/scenario-05/scenario-05.1-post-consents.json, f3-pagamentos/scenario-05/scenario-05.2-get-consents.json, f3-pagamentos/scenario-05/scenario-05.3-post-pix-payments.json, f3-pagamentos/scenario-05/scenario-05.4-get-pix-payments.json
=> 1.0.1-rc1.1 MANU CACC

f3-pagamentos/scenario-06/scenario-06.3-post-pix-payments.json, f3-pagamentos/scenario-06/scenario-06.4-get-pix-payments.json
=> 1.0.1-rc1.1 MANU TRAN

f3-pagamentos/README.md, f3-pagamentos/scenario-09/readme.md, f3-pagamentos/scenario-09/scenario-09.1-post-consents.json, f3-pagamentos/scenario-09/scenario-09.2-get-consents.json, f3-pagamentos/scenario-09/scenario-09.3-post-pix-payments.json, f3-pagamentos/scenario-09/scenario-09.4-get-pix-payments.json
=> 1.0.1-rc1.1 INIC chave e-mail

f3-pagamentos/README.md, f3-pagamentos/scenario-10/readme.md, f3-pagamentos/scenario-10/scenario-10.1-post-consents.json, f3-pagamentos/scenario-10/scenario-10.2-get-consents.json, f3-pagamentos/scenario-10/scenario-10.3-post-pix-payments.json, f3-pagamentos/scenario-10/scenario-10.4-get-pix-payments.json
=> 1.0.1-rc1.1 INIC chave cnpj

f3-pagamentos/README.md, f3-pagamentos/scenario-12/readme.md, f3-pagamentos/scenario-12/scenario-12.1-post-consents.json, f3-pagamentos/scenario-12/scenario-12.2-get-consents.json, f3-pagamentos/scenario-12/scenario-12.3-post-pix-payments.json, f3-pagamentos/scenario-12/scenario-12.4-get-pix-payments.json
1.01-rc1.1 Multipla alcada pendente de autorizacao
=> 1.01-rc1.1 Multipla alcada pendente de autorizacao

f3-pagamentos/README.md, f3-pagamentos/cenario-15/cenario-15.1-post-consents.json, f3-pagamentos/cenario-15/cenario-15.2-get-consents.json, f3-pagamentos/cenario-15/cenario-15.3-post-pix-payments.json, f3-pagamentos/cenario-15/cenario-15.4-get-pix-payments.json, f3-pagamentos/cenario-15/readme.md
Adaptação do cenário de QRDN com o proxy e dados de pagador e recebedor informados pela Raidiam por e-mail para testes de conformidade.
=> 1.0.1-rc1.2 QRDN - Sucesso com chave telefone

f3-pagamentos/cenario-15/cenario-15.1-post-consents.json, f3-pagamentos/cenario-15/cenario-15.2-get-consents.json, f3-pagamentos/cenario-16/cenario-16.1-post-consents.json, f3-pagamentos/cenario-16/cenario-16.2-get-consents.json
Conforme issue aberta pelo Erick alteramos o cpf para ser reconhecido pelo DICT.
=> Alteração de cpf

f3-pagamentos/cenario-15/cenario-15.1-post-consents.json, f3-pagamentos/cenario-15/cenario-15.2-get-consents.json
Alterado o QR para que se torne reutilizável e feitas revisões gerais no código de QR.
=> Alteração de QRCode para ser reutilizável e revisão

f3-pagamentos/cenario-16/cenario-16.1-post-consents.json, f3-pagamentos/cenario-16/cenario-16.2-get-consents.json
=> 1.0.1 QRES - sucesso com chave e-mail

dados-cadastrais-e-transacionais/consentimento/post-consents/post-consents-1.1.json
Atualização de massa da persona 01.
=> Persona 01

dados-abertos/creditcards-opendata/get-business-credit-cards/get-business-credit-cards-1.0.0-beta.1.json, dados-abertos/creditcards-opendata/get-personal-credit-cards/get-personal-credit-cards-1.0.0-beta.1.json
Criando massas para api opendata creditcards
=> 1.0.0-beta.1 opendata creditcards

dados-abertos/financings-opendata/get-business-financings/get-business-financings-1.0.0-beta.1.json, dados-abertos/financings-opendata/get-personal-financings/get-personal-financings-1.0.0-beta.1.json
Criar massa api financings opendata
=> 1.0.0-beta.1 opendata financings

dados-abertos/investimentos/cambio/get_operations_operationId_events_v1.0.0-rc1.0.json, dados-abertos/investimentos/cambio/get_operations_operationId_v1.0.0-rc1.0.json, dados-abertos/investimentos/cambio/get_operations_v1.0.0-rc1.0.json
Criando massa para api exchanges versao 1.0.0-rc1.0
=> 1.0.0-rc1.0 exchanges 

dados-abertos/adiantamento-a-depositantes-opendata/get-business-unarranged-account-overdraft/get-business-unarranged-account-overdraft-1.0.0-beta.1.json, dados-abertos/adiantamento-a-depositantes-opendata/get-personal-unarranged-account-overdraft/get-personal-unarranged-accounts-overdraft-1.0.0-beta.1.json, dados-abertos/adiantamento-de-recebiveis-opendata/get-business-invoice-financings/get-business-invoice-financings-1.0.0-beta.1.json, dados-abertos/adiantamento-de-recebiveis-opendata/get-personal-invoice-financings/get-personal-invoice-financings-1.0.0-beta.1.json, dados-abertos/cartao-de-credito-opendata/get-business-credit-cards/get-business-credit-cards-1.0.0-beta.1.json, dados-abertos/cartao-de-credito-opendata/get-personal-credit-cards/get-personal-credit-cards-1.0.0-beta.1.json, dados-abertos/emprestimos-opendata/get-business-loans/get-business-loans-1.0.0-beta.1.json, dados-abertos/emprestimos-opendata/get-personal-loans/get-personal-loans-1.0.0-beta.1.json, dados-abertos/financiamentos-opendata/get-business-financings/get-business-financings-1.0.0-beta.1.json, dados-abertos/financiamentos-opendata/get-personal-financings/get-personal-financings-1.0.0-beta.1.json
=> 1.0.0-beta.1 apis opendata

relatorios-e-metricas/admin/metrics-v2.0.0-beta.2/cenario-01-get-metrics.json, relatorios-e-metricas/admin/metrics-v2.0.0-beta.2/cenario-02-get-metrics.json, relatorios-e-metricas/admin/metrics-v2.0.0-beta.2/cenario-03-get-metrics.json, relatorios-e-metricas/admin/metrics-v2.0.0-beta.2/cenario-04-get-metrics.json
Criando massas para a versão 2.0.0-beta.2
=> 2.0.0-beta.2 admin
